### ISSUE TITLE
2003 baseline paper

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/LDAClassification#2]
According to Manny, this was the [baseline paper](http://www.jmlr.org/papers/volume3/blei03a/blei03a.pdf) - Pg 1012 which he talked about for feature reduction.
- They evaluated using accuracy, and doc topic weight features for SVM classifier.
- K=50 constant. Dataset used was Reuters-21578.

I ran similar experiment(k=50) on our manny mock datasets. Results are really bad. fscore of less than 10%. Even with tuning it had no effect. **This could be because of highly unbalanced classes that even smote couldnt help.**

**Comment by amritbhanu** [comment]
- [ ] next step is to run it on Reuters dataset and see if tuning and not tuning helps or not.

**Comment by timm** [comment]
ok

so you've got something to show to LN on thrusday. cool.

**Comment by amritbhanu** [comment]
there was a bug prof. Please ignore this issue. I am waiting for further results.
