### ISSUE TITLE
Weekly Report - 18/11/2016

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/LDAClassification#7]
## DOING:
- Working on these todo lists #6 :
## Running:
- Does stability help classification? Tuned and untuned? Multigoal fscore and jaccard score
- Heat Map with tags and topics for different datasets. (With tuning)
- Tune svm and lda, just for fscore (kernel, C, degree, learning rate)
## roadblocks:
- Nothing yet
## admin:
- No

**Comment by timm** [comment]
ok

**Comment by timm** [comment]
we need those charts on "tuning improves classification" as part of the icse replies

**Comment by amritbhanu** [comment]
on it

**Comment by amritbhanu** [comment]
## Results:
- Solid lines represents tuned results and dotted lines untuned.
- tuning improves f2scores by minimum 25-30% than untuned settings.
- tuning improves raw scores (jaccard) by minimum 80% and maximum of 200%

![file](https://github.com/ai-se/LDAClassification/raw/master/src/2016-10-11/raw_vs_f.png)
